name: Legym-automation

on:
  workflow_dispatch: # 支持手动触发工作流
  schedule:          # 定时触发工作流
    - cron: '0 13 * * *' # 每天 UTC 时间 13:00 触发

env:
  TZ: 'Asia/Shanghai' # 设置时区为上海

jobs:
  build:
    runs-on: windows-latest # 使用最新的 Windows 环境

    steps:
      - uses: actions/checkout@v3 # 检出代码

      - uses: actions/setup-python@v4 # 设置 Python 环境
        with:
          python-version: 3.9
          architecture: 'x64'

      - run: |
          python -m pip install --upgrade pip
          pip install -i https://test.pypi.org/simple/ legym==0.4
          python main.py ${{ secrets.username }}#${{ secrets.password }}#${{ secrets.distance }}#${{ secrets.activity }}

